### ISSUE TITLE
conflict with EPEL

### ISSUE THREAD

**Issue by Saladin1812** [iusrepo/python36u#8]
python36 actually now is available on EPEL it was moved yesterday from EPEL testing to EPEL. So when we try to install python36u it conflicts with EPEL. To fix this i had to go to epel.repo and exclude=python36* packages so that i can use packages from IUS. Please fix this for an average user.

**Comment by carlwgeorge** [comment]
python36 and python36u are the same upstream software, and contain many of the same file paths, so of course they conflict with each other.  Why are you trying to install both?  What exact conflict are you seeing?  What behavior did you expect to see?

**Comment by Saladin1812** [comment]
python36 is not installed but EPEL is enabled, even if you install python36u with python36 not on the system it will give you error.. I tried on new centos install with EPEL and IUS enabled it wont let u install no matter python36 in installed or not.. For that you have to make EPEL exclude the python36 package so i edited epel.repo..

**Comment by Saladin1812** [comment]
Im not trying to install both just python36u from IUS but EPEL is just enabled because of other softwares.. I didnt even touched python36 u can test it yourself..

**Comment by carlwgeorge** [comment]
I asked for the exact error you are seeing because I can not reproduce what you have described.

Here is the output of installing python36u in a fresh CentOS container.  Note that EPEL is enabled when I install it because installing ius-release pulls in epel-release as a dependency.

```
$ podman run -it --rm centos:7
[root@2b2ddf71ba3c /]# yum -q -y install https://centos7.iuscommunity.org/ius-release.rpm
warning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-11.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for epel-release-7-11.noarch.rpm is not installed
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-6.1810.2.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
[root@2b2ddf71ba3c /]# yum -q repolist
repo id                                       repo name                                                                           status
base/7/x86_64                                 CentOS-7 - Base                                                                     10019
epel/x86_64                                   Extra Packages for Enterprise Linux 7 - x86_64                                      13030
extras/7/x86_64                               CentOS-7 - Extras                                                                     385
ius/x86_64                                    IUS Community Packages for Enterprise Linux 7 - x86_64                                578
updates/7/x86_64                              CentOS-7 - Updates                                                                   1477
[root@2b2ddf71ba3c /]# yum -q -y install python36u
warning: /var/cache/yum/x86_64/7/ius/packages/python36u-3.6.7-1.ius.centos7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 9cd4953f: NOKEY
Public key for python36u-3.6.7-1.ius.centos7.x86_64.rpm is not installed
Importing GPG key 0x9CD4953F:
 Userid     : "IUS Community Project <coredev@iuscommunity.org>"
 Fingerprint: 8b84 6e3a b3fe 6462 74e8 670f da22 1cdf 9cd4 953f
 Package    : ius-release-1.0-15.ius.centos7.noarch (installed)
 From       : /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
[root@2b2ddf71ba3c /]# rpm -q python36u
python36u-3.6.7-1.ius.centos7.x86_64
[root@2b2ddf71ba3c /]# python3.6 --version
Python 3.6.7
```

**Comment by Saladin1812** [comment]
you used -q and -y arguement.. Without that it might give u an error.

**Comment by carlwgeorge** [comment]
It doesn't.  `-q` is for quiet to remove the less relevant output since I was pasting it here.  `-y` means assume yes, rather than having to press y to proceed.  Neither of those change the dependency resolution or conflict checks.  I even confirmed this 100% and re-ran the commands without those flags and got the same results.

Since you won't share the error you're getting there isn't anything I can do here.
